//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class card
    {
        public int cardId { get; set; }
        public Nullable<int> bankId { get; set; }
        public string cardName { get; set; }
        public string imageUrl { get; set; }
        public Nullable<decimal> creditLimit { get; set; }
        public Nullable<decimal> annualFee { get; set; }
        public Nullable<decimal> intRate { get; set; }
    
        public virtual bank bank { get; set; }
    }
}
