USE [master]
GO

/****** Object:  Database [moneyworks]    Script Date: 7/3/2018 2:28:08 PM ******/
CREATE DATABASE [moneyworks]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'moneyworks', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SARASASQL\MSSQL\DATA\moneyworks.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'moneyworks_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SARASASQL\MSSQL\DATA\moneyworks_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [moneyworks] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [moneyworks].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [moneyworks] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [moneyworks] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [moneyworks] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [moneyworks] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [moneyworks] SET ARITHABORT OFF 
GO

ALTER DATABASE [moneyworks] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [moneyworks] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [moneyworks] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [moneyworks] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [moneyworks] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [moneyworks] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [moneyworks] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [moneyworks] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [moneyworks] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [moneyworks] SET  DISABLE_BROKER 
GO

ALTER DATABASE [moneyworks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [moneyworks] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [moneyworks] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [moneyworks] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [moneyworks] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [moneyworks] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [moneyworks] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [moneyworks] SET RECOVERY FULL 
GO

ALTER DATABASE [moneyworks] SET  MULTI_USER 
GO

ALTER DATABASE [moneyworks] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [moneyworks] SET DB_CHAINING OFF 
GO

ALTER DATABASE [moneyworks] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [moneyworks] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [moneyworks] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [moneyworks] SET QUERY_STORE = OFF
GO

USE [moneyworks]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [moneyworks] SET  READ_WRITE 
GO

